### ISSUE TITLE
Add new technician role

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1919] opened 2020-08-18 10:22 UTC
Add new technician role similar to admin in terms of view but with restricted editing access.

Feedback from customer

**Comment by jerome-benoit** [comment] 2020-08-18 18:16
It's a duplicate of https://github.com/LucasBrazi06/ev-dashboard/issues/1871

**Comment by LucasBrazi06** [comment] 2020-10-11 15:58
Dups

**Closed by LucasBrazi06** 2020-10-11 15:58 UTC
Labels: feature, high-prio
