### ISSUE TITLE
Car: Add Car Catalog filter in Car Management

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#2062] opened 2020-11-01 17:54 UTC
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/99d53e49-c8a9-4e7d-8ca4-769296141db3)

**Comment by WillyLellouch** [comment] 2021-01-15 12:17
Works as intended, closing issue

**Closed by WillyLellouch** 2021-01-15 12:17 UTC
Labels: enhancement, high-prio
