### ISSUE TITLE
Sessions > Start: Start a session by selecting the car and the badge

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1952] opened 2020-09-07 13:55 UTC

**Comment by LucasBrazi06** [comment] 2020-10-29 21:57
@mahdibenromdhane 
Could you merge with master-qa?
Thanks.

**Comment by mahdibenromdhane** [comment] 2020-10-30 10:24
> @mahdibenromdhane
> Could you merge with master-qa?
> Thanks.

Done :)

**Comment by LucasBrazi06** [comment] 2020-11-27 19:51
Violation of rule #30 ;-)
30 Keep your branch or pull request up to date with master-qa on daily basis

**Comment by mahdibenromdhane** [comment] 2020-11-30 15:32
> Violation of rule #30 ;-)
> 30 Keep your branch or pull request up to date with master-qa on daily basis

Done :)

**Comment by LucasBrazi06** [comment] 2020-12-01 18:45
@mahdibenromdhane just one remark I haven't yet checked, could you tell me if when the roaming is active you cannot select a Roaming user at all as well as the corresponding roaming badges?
This should be blocked in the backend also.
Let me know.

**Comment by mahdibenromdhane** [comment] 2020-12-01 19:34
> @mahdibenromdhane just one remark I haven't yet checked, could you tell me if when the roaming is active you cannot select a Roaming user at all as well as the corresponding roaming badges?
> This should be blocked in the backend also.
> Let me know.

This use case is not handled, I will fix it and push it

**Comment by LucasBrazi06** [comment] 2020-12-01 21:22
> This use case is not handled, I will fix it and push it

Thanks a lot!
I think we have the same kind of issue but for the Filters.
Just double check in all the lists that every filters/asssignment... is filtered using the org filter value/es

**Comment by mahdibenromdhane** [comment] 2020-12-01 21:35
> > This use case is not handled, I will fix it and push it
> 
> Thanks a lot!
> I think we have the same kind of issue but for the Filters.
> Just double check in all the lists that every filters/asssignment... is filtered using the org filter value/es

Ok i will double check the other cases.

**Comment by WillyLellouch** [comment] 2020-12-08 13:50
![1952-1](https://user-images.githubusercontent.com/47318405/101491314-e31ff500-3963-11eb-878b-ed2f2176c2de.png)

I assigned a car to myself that was already created by someone else as my default car.
As in screenshot, the car does not appear to be assigned as a default car in the table.
After refresh, the car still is noted as not default in the list. When editing the car, the default checkbox is still checked.

**Comment by LucasBrazi06** [comment] 2020-12-08 14:46
@WillyLellouch Just fixed this bug few hours ago :)
Fix will be deployed tonight.

**Comment by WillyLellouch** [comment] 2020-12-09 08:19
@LucasBrazi06 is it still a requirement to disable the car field if there is no car to assign ?

**Comment by LucasBrazi06** [comment] 2020-12-09 08:22
> is it still a requirement to disable the car field if there is no car to assign ?

Yes, the car is not mandatory ;-)

**Comment by WillyLellouch** [comment] 2020-12-09 13:13
Works as intended :
- User field only appears for Admin, Basic users always starts session for themselves
- If there is a default car or a default badge they are automatically added, if none of the cars or none of the badges are default the fields stay empty
- Roaming Users cannot be selected
- Car is displayed in session pop-up

Does not work as intended :
- Car field is not disabled if there is no car to select
- Car does not appear in the Charging Sessions list / Connector details
- There is no migration task that sets the default tag when only one badge is assigned to a user or it is not running

**Comment by WillyLellouch** [comment] 2020-12-09 13:19
As of last version of master-qa, I can no longer see the car I chose in the session pop-up

![1952-2.png](https://images.zenhubusercontent.com/5e0da5432dae1dea3f211ec9/03966eff-3c08-43a7-8b07-a4fe16a6124a)

**Comment by WillyLellouch** [comment] 2020-12-09 13:22
Disregard the previous comment it was my mistake

**Comment by LucasBrazi06** [comment] 2020-12-09 13:50
> * Car field is not disabled if there is no car to select
What do you mean by not disabled?
Normally we do not disable the field.

> * Car does not appear in the Charging Sessions list / Connector details
It was not required for a first release but we can add it.
Could you open an issue and assign it to Mahdi?
Thanks.

> * There is no migration task that sets the default tag when only one badge is assigned to a user or it is not running
Yes there is one called SetDefaultTagToUserTask.
You can check with Mahdi also if we need to run this task again.

**Comment by WillyLellouch** [comment] 2020-12-09 13:58
@LucasBrazi06 ![1952-3.png](https://images.zenhubusercontent.com/5e0da5432dae1dea3f211ec9/505ba84b-ae5a-4580-b774-1e964fd102ef)

For the migration task OK I missed it I'll test it

I'll also open a new issue for the second point

**Comment by WillyLellouch** [comment] 2020-12-10 07:25
The migration task is also working properly.
Everything good on my end if the car field is not an issue.

**Comment by WillyLellouch** [comment] 2021-01-15 08:25
Since there doesn't seem to be anymore issues here, I'll close the issue

**Closed by WillyLellouch** 2021-01-15 08:25 UTC
Labels: feature, high-prio
