### ISSUE TITLE
Transaction History - New table button to 'Navigate To Charge Plan'

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1849] opened 2020-07-21 15:07 UTC
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/7e80a1fa-cf29-40f6-8c1a-1d6f67c945ce)

**Comment by LucasBrazi06** [comment] 2020-07-21 15:25
Maybe not possible as charging plan is applied for the transaction only when Smart Charging is active and is deleted just after.

**Comment by LucasBrazi06** [comment] 2020-08-02 09:59
Jump to charging plans with filtering on Charging Station ID + Connector ID

**Comment by LucasBrazi06** [comment] 2020-10-27 09:33
@mahdibenromdhane could you provide also this table action to the Session In Progress list?
Thanks.

**Comment by mahdibenromdhane** [comment] 2020-10-27 14:45
> @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> Thanks.

Done :)

**Comment by LucasBrazi06** [comment] 2020-10-27 19:59
> > @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> > Thanks.
> 
> Done :)

Thanks!
PR?

**Comment by mahdibenromdhane** [comment] 2020-10-27 20:09
> > > @mahdibenromdhane could you provide also this table action to the Session In Progress list?
> > > Thanks.
> > 
> > 
> > Done :)
> 
> Thanks!
> PR?
I have connected to a wrong issue, now it's good
https://github.com/LucasBrazi06/ev-dashboard/pull/2047

**Comment by WillyLellouch** [comment] 2021-01-15 12:53
Tested with multiple combinations of charging plans and sessions. Works as intended, closing issue

**Closed by WillyLellouch** 2021-01-15 12:53 UTC
Labels: enhancement, high-prio
