### ISSUE TITLE
Settings > Tokens: Site Area must be hidden when organization is inactive (column in list + input field in pop-up)

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1932] opened 2020-08-28 21:24 UTC
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/9943d20e-27b3-40d3-a00b-5d2f03c922d0)

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/b5a28dc0-87c3-4519-a8cb-c68827b40c46)

**Comment by WillyLellouch** [comment] 2021-01-15 08:49
This works as intended. Closing issue.

**Closed by WillyLellouch** 2021-01-15 08:49 UTC
Labels: bug, high-prio
