### ISSUE TITLE
Site area without charging station must not be sent

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-dashboard#1822] opened 2020-07-10 08:50 UTC

**Comment by jerome-benoit** [comment] 2020-07-16 18:48
Should be finally fixed in https://github.com/LucasBrazi06/ev-server/pull/1683

**Comment by LucasBrazi06** [comment] 2020-07-16 19:17
> Should be finally fixed in [LucasBrazi06/ev-server#1683](https://github.com/LucasBrazi06/ev-server/pull/1683)

I believed it was already fixed last friday, what went wrong?

**Comment by jerome-benoit** [comment] 2020-07-16 19:59
> > Should be finally fixed in [LucasBrazi06/ev-server#1683](https://github.com/LucasBrazi06/ev-server/pull/1683)
> 
> I believed it was already fixed last friday, what went wrong?

At the connector OCPI location level, duplicated records was sent for each OCPI evse connector. 

The root cause is that at the site area level, the code was still adding site areas with no charging stations. It's not strictly speaking the very same issue but it's really strongly related to the previous changes to fix it that have reveal the records duplication.

**Comment by LucasBrazi06** [comment] 2020-07-17 07:06
> > > Should be finally fixed in [LucasBrazi06/ev-server#1683](https://github.com/LucasBrazi06/ev-server/pull/1683)
> > 
> > 
> > I believed it was already fixed last friday, what went wrong?
> 
> At the connector OCPI location level, duplicated records was sent for each OCPI evse connector.
> 
> The root cause is that at the site area level, the code was still adding site areas with no charging stations. It's not strictly speaking the very same issue but it's really strongly related to the previous changes to fix it that have reveal the records duplication.

Ok thanks!
Do you think that this kind of issue could have been found on our QA system where we have a test tenant with Gireve?

**Comment by jerome-benoit** [comment] 2020-07-17 10:06
> > > > Should be finally fixed in [LucasBrazi06/ev-server#1683](https://github.com/LucasBrazi06/ev-server/pull/1683)
> > > 
> > > 
> > > I believed it was already fixed last friday, what went wrong?
> > 
> > 
> > At the connector OCPI location level, duplicated records was sent for each OCPI evse connector.
> > The root cause is that at the site area level, the code was still adding site areas with no charging stations. It's not strictly speaking the very same issue but it's really strongly related to the previous changes to fix it that have reveal the records duplication.
> 
> Ok thanks!
> Do you think that this kind of issue could have been found on our QA system where we have a test tenant with Gireve?

Sure, most of the latest OCPI issues can be unit tested.

**Comment by LucasBrazi06** [comment] 2020-07-17 10:16
@fcoutellier As discussed, it would be nice to have unit tests on OCPI (at least the most important ones)

**Closed** 2020-07-24 15:28 UTC
Labels: god-prio
